package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/charmbracelet/huh"
	"github.com/fractalops/ssmx/internal/config"
	"github.com/fractalops/ssmx/internal/tui"
)

func runConfigInteractive() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	var action string
	if err := huh.NewSelect[string]().
		Title("ssmx config").
		Options(
			huh.NewOption("Manage bookmarks", "bookmarks"),
			huh.NewOption("Set default profile", "profile"),
			huh.NewOption("Set default region", "region"),
			huh.NewOption("Generate SSH config", "ssh"),
			huh.NewOption("Show config path", "path"),
		).
		Value(&action).
		Run(); err != nil {
		return nil // user cancelled
	}

	switch action {
	case "bookmarks":
		return runManageBookmarks(cfg)

	case "profile":
		if err := huh.NewInput().
			Title("Default AWS profile").
			Value(&cfg.DefaultProfile).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "region":
		if err := huh.NewInput().
			Title("Default AWS region").
			Placeholder("us-east-1").
			Value(&cfg.DefaultRegion).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "ssh":
		return runSSHGen()

	case "path":
		dir, err := config.Dir()
		if err != nil {
			return err
		}
		fmt.Println(filepath.Join(dir, "config.yaml"))
	}
	return nil
}

func runManageBookmarks(cfg *config.Config) error {
	if len(cfg.Aliases) == 0 {
		fmt.Println(tui.StyleDim.Render("  No bookmarks yet. They're saved automatically after connecting."))
		return nil
	}

	// Build a select list of existing bookmarks.
	type bookmark struct{ name, id string }
	var bookmarks []bookmark
	for name, id := range cfg.Aliases {
		bookmarks = append(bookmarks, bookmark{name, id})
	}

	// Sort for stable display.
	sort.Slice(bookmarks, func(i, j int) bool {
		return bookmarks[i].name < bookmarks[j].name
	})

	opts := make([]huh.Option[string], 0, len(bookmarks))
	for _, b := range bookmarks {
		label := fmt.Sprintf("%-25s %s", b.name, tui.StyleDim.Render(b.id))
		opts = append(opts, huh.NewOption(label, b.name))
	}

	var selected string
	if err := huh.NewSelect[string]().
		Title("Bookmarks — select to edit").
		Options(opts...).
		Value(&selected).
		Run(); err != nil {
		return nil
	}

	instanceID := cfg.Aliases[selected]

	var action string
	if err := huh.NewSelect[string]().
		Title(selected + "  →  " + instanceID).
		Options(
			huh.NewOption("Rename", "rename"),
			huh.NewOption("Remove", "remove"),
		).
		Value(&action).
		Run(); err != nil {
		return nil
	}

	switch action {
	case "rename":
		newName := selected
		if err := huh.NewInput().
			Title("New name").
			Value(&newName).
			Run(); err != nil || newName == "" || newName == selected {
			return nil
		}
		if err := config.RemoveAlias(selected); err != nil {
			return err
		}
		if err := config.SetAlias(newName, instanceID); err != nil {
			return err
		}
		fmt.Printf("%s  Renamed %s → %s\n", tui.StyleSuccess.Render("ok"), tui.StyleBold.Render(selected), tui.StyleBold.Render(newName))

	case "remove":
		if err := config.RemoveAlias(selected); err != nil {
			return err
		}
		fmt.Printf("%s  Removed bookmark %s\n", tui.StyleSuccess.Render("ok"), tui.StyleBold.Render(selected))
	}
	return nil
}

const sshConfigTemplate = `# Generated by ssmx — do not edit manually.
# Re-generate with: ssmx --configure

{{range .Aliases}}
Host {{.Name}}
    IdentityFile ~/.ssh/id_rsa
    User ec2-user
    ProxyCommand ssmx connect --instance-id {{.InstanceID}} --ssh-proxy
{{end}}

# Catch-all for instance IDs.
Host i-* mi-*
    User ec2-user
    ProxyCommand ssmx connect --instance-id %h --ssh-proxy
`

type sshAlias struct {
	Name       string
	InstanceID string
}

func runSSHGen() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	var aliases []sshAlias
	for name, id := range cfg.Aliases {
		aliases = append(aliases, sshAlias{Name: name, InstanceID: id})
	}

	tmpl, err := template.New("ssh").Parse(sshConfigTemplate)
	if err != nil {
		return err
	}

	sshDir := filepath.Join(os.Getenv("HOME"), ".ssh", "config.d")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("creating %s: %w", sshDir, err)
	}
	outPath := filepath.Join(sshDir, "ssmx")

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating SSH config: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, map[string]interface{}{"Aliases": aliases}); err != nil {
		return err
	}

	fmt.Printf("%s  Written to %s\n", tui.StyleSuccess.Render("ok"), outPath)
	fmt.Println()
	fmt.Println(tui.StyleDim.Render("  Add this to your ~/.ssh/config:"))
	fmt.Printf("    %s\n", tui.StyleBold.Render("Include ~/.ssh/config.d/ssmx"))
	return nil
}
