package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/charmbracelet/huh"
	"github.com/fractalops/ssmx/internal/config"
	"github.com/fractalops/ssmx/internal/tui"
	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage ssmx settings, aliases, and SSH config",
	RunE:  runConfigInteractive,
}

var configAliasCmd = &cobra.Command{
	Use:   "alias <name> <instance-id>",
	Short: "Create or update an alias for an instance ID",
	Args:  cobra.ExactArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		name, id := args[0], args[1]
		if err := config.SetAlias(name, id); err != nil {
			return err
		}
		fmt.Printf("%s  Alias %s → %s saved\n", tui.StyleSuccess.Render("ok"), tui.StyleBold.Render(name), id)
		return nil
	},
}

var configSSHGenCmd = &cobra.Command{
	Use:   "ssh-gen",
	Short: "Generate ~/.ssh/config.d/ssmx with ProxyCommand entries",
	RunE:  runSSHGen,
}

func init() {
	configCmd.AddCommand(configAliasCmd)
	configCmd.AddCommand(configSSHGenCmd)
	rootCmd.AddCommand(configCmd)
}

func runConfigInteractive(cmd *cobra.Command, args []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	var action string
	if err := huh.NewSelect[string]().
		Title("ssmx config").
		Options(
			huh.NewOption("Set default profile", "profile"),
			huh.NewOption("Set default region", "region"),
			huh.NewOption("Add alias", "alias"),
			huh.NewOption("Generate SSH config", "ssh"),
			huh.NewOption("Show config path", "path"),
		).
		Value(&action).
		Run(); err != nil {
		return nil // user cancelled
	}

	switch action {
	case "profile":
		if err := huh.NewInput().
			Title("Default AWS profile").
			Value(&cfg.DefaultProfile).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "region":
		if err := huh.NewInput().
			Title("Default AWS region").
			Placeholder("us-east-1").
			Value(&cfg.DefaultRegion).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "alias":
		var name, id string
		if err := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().Title("Alias name").Value(&name),
				huh.NewInput().Title("Instance ID").Value(&id),
			),
		).Run(); err != nil {
			return nil
		}
		return config.SetAlias(name, id)

	case "ssh":
		return runSSHGen(cmd, args)

	case "path":
		dir, err := config.Dir()
		if err != nil {
			return err
		}
		fmt.Println(filepath.Join(dir, "config.yaml"))
	}
	return nil
}

const sshConfigTemplate = `# Generated by ssmx — do not edit manually.
# Re-generate with: ssmx config ssh-gen

{{range .Aliases}}
Host {{.Name}}
    IdentityFile ~/.ssh/id_rsa
    User ec2-user
    ProxyCommand ssmx connect --instance-id {{.InstanceID}} --ssh-proxy
{{end}}

# Catch-all for instance IDs.
Host i-* mi-*
    User ec2-user
    ProxyCommand ssmx connect --instance-id %h --ssh-proxy
`

type sshAlias struct {
	Name       string
	InstanceID string
}

func runSSHGen(cmd *cobra.Command, args []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	var aliases []sshAlias
	for name, id := range cfg.Aliases {
		aliases = append(aliases, sshAlias{Name: name, InstanceID: id})
	}

	tmpl, err := template.New("ssh").Parse(sshConfigTemplate)
	if err != nil {
		return err
	}

	sshDir := filepath.Join(os.Getenv("HOME"), ".ssh", "config.d")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("creating %s: %w", sshDir, err)
	}
	outPath := filepath.Join(sshDir, "ssmx")

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating SSH config: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, map[string]interface{}{"Aliases": aliases}); err != nil {
		return err
	}

	fmt.Printf("%s  Written to %s\n", tui.StyleSuccess.Render("ok"), outPath)
	fmt.Println()
	fmt.Println(tui.StyleDim.Render("  Add this to your ~/.ssh/config:"))
	fmt.Printf("    %s\n", tui.StyleBold.Render("Include ~/.ssh/config.d/ssmx"))
	return nil
}
