package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/charmbracelet/huh"
	"github.com/fractalops/ssmx/internal/config"
	sshpkg "github.com/fractalops/ssmx/internal/ssh"
	"github.com/fractalops/ssmx/internal/tui"
)

func runConfigInteractive() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	var action string
	if err := huh.NewSelect[string]().
		Title("ssmx config").
		Options(
			huh.NewOption("Manage bookmarks", "bookmarks"),
			huh.NewOption("Set default profile", "profile"),
			huh.NewOption("Set default region", "region"),
			huh.NewOption("Generate SSH config", "ssh"),
			huh.NewOption("Show config path", "path"),
		).
		Value(&action).
		Run(); err != nil {
		return nil // user cancelled
	}

	switch action {
	case "bookmarks":
		return runManageBookmarks(cfg)

	case "profile":
		if err := huh.NewInput().
			Title("Default AWS profile").
			Value(&cfg.DefaultProfile).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "region":
		if err := huh.NewInput().
			Title("Default AWS region").
			Placeholder("us-east-1").
			Value(&cfg.DefaultRegion).
			Run(); err != nil {
			return nil
		}
		return config.Save(cfg)

	case "ssh":
		return runSSHGen()

	case "path":
		dir, err := config.Dir()
		if err != nil {
			return err
		}
		fmt.Println(filepath.Join(dir, "config.yaml"))
	}
	return nil
}

func runManageBookmarks(cfg *config.Config) error {
	if len(cfg.Aliases) == 0 {
		fmt.Println(tui.StyleDim.Render("  No bookmarks yet. They're saved automatically after connecting."))
		return nil
	}

	// Build a select list of existing bookmarks.
	type bookmark struct{ name, id string }
	var bookmarks []bookmark
	for name, id := range cfg.Aliases {
		bookmarks = append(bookmarks, bookmark{name, id})
	}

	// Sort for stable display.
	sort.Slice(bookmarks, func(i, j int) bool {
		return bookmarks[i].name < bookmarks[j].name
	})

	opts := make([]huh.Option[string], 0, len(bookmarks))
	for _, b := range bookmarks {
		label := fmt.Sprintf("%-25s %s", b.name, tui.StyleDim.Render(b.id))
		opts = append(opts, huh.NewOption(label, b.name))
	}

	var selected string
	if err := huh.NewSelect[string]().
		Title("Bookmarks — select to edit").
		Options(opts...).
		Value(&selected).
		Run(); err != nil {
		return nil
	}

	instanceID := cfg.Aliases[selected]

	var action string
	if err := huh.NewSelect[string]().
		Title(selected + "  →  " + instanceID).
		Options(
			huh.NewOption("Rename", "rename"),
			huh.NewOption("Remove", "remove"),
		).
		Value(&action).
		Run(); err != nil {
		return nil
	}

	switch action {
	case "rename":
		newName := selected
		if err := huh.NewInput().
			Title("New name").
			Value(&newName).
			Run(); err != nil || newName == "" || newName == selected {
			return nil
		}
		if err := config.RemoveAlias(selected); err != nil {
			return err
		}
		if err := config.SetAlias(newName, instanceID); err != nil {
			return err
		}
		fmt.Printf("%s  Renamed %s → %s\n", tui.StyleSuccess.Render("ok"), tui.StyleBold.Render(selected), tui.StyleBold.Render(newName))

	case "remove":
		if err := config.RemoveAlias(selected); err != nil {
			return err
		}
		fmt.Printf("%s  Removed bookmark %s\n", tui.StyleSuccess.Render("ok"), tui.StyleBold.Render(selected))
	}
	return nil
}

const sshConfigTemplate = `# Generated by ssmx — do not edit manually.
# Re-generate with: ssmx --configure
# Requires ec2-instance-connect on instances (pre-installed on standard AMIs).
{{range .Aliases}}
Host {{.Name}}
    HostName {{.InstanceID}}
    User ec2-user
    IdentityFile {{$.KeyPath}}
    ProxyCommand ssmx --proxy %h %r
{{end}}
# Catch-all for raw instance IDs.
Host i-* mi-*
    IdentityFile {{.KeyPath}}
    ProxyCommand ssmx --proxy %h %r
    StrictHostKeyChecking accept-new
`

type sshAlias struct {
	Name       string
	InstanceID string
}

func runSSHGen() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	// Key selection — prompt once, save to config.
	if cfg.SSHKeyPath == "" {
		keyPath, err := promptKeySelection()
		if err != nil {
			return err
		}
		cfg.SSHKeyPath = keyPath
		if err := config.SetSSHKeyPath(keyPath); err != nil {
			return err
		}
	}

	var aliases []sshAlias
	for name, id := range cfg.Aliases {
		aliases = append(aliases, sshAlias{Name: name, InstanceID: id})
	}

	tmpl, err := template.New("ssh").Parse(sshConfigTemplate)
	if err != nil {
		return err
	}

	sshDir := filepath.Join(os.Getenv("HOME"), ".ssh", "config.d")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("creating %s: %w", sshDir, err)
	}
	outPath := filepath.Join(sshDir, "ssmx")

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating SSH config: %w", err)
	}
	defer f.Close()

	keyPath := cfg.SSHKeyPath
	if keyPath == "" {
		home, _ := os.UserHomeDir()
		keyPath = filepath.Join(home, ".ssmx", "ssh_key")
	}

	if err := tmpl.Execute(f, map[string]interface{}{
		"Aliases": aliases,
		"KeyPath": keyPath,
	}); err != nil {
		return err
	}

	fmt.Printf("%s  SSH config written to %s\n", tui.StyleSuccess.Render("ok"), outPath)
	fmt.Println()
	fmt.Println(tui.StyleDim.Render("  Add this to your ~/.ssh/config:"))
	fmt.Printf("    %s\n", tui.StyleBold.Render("Include ~/.ssh/config.d/ssmx"))
	fmt.Println()
	fmt.Println(tui.StyleDim.Render("  Instances need ec2-instance-connect installed."))
	fmt.Println(tui.StyleDim.Render("  Standard Amazon Linux and Ubuntu AMIs include it by default."))
	return nil
}

func promptKeySelection() (string, error) {
	defaultPath := sshpkg.DefaultKeyPath()

	var opts []huh.Option[string]
	if defaultPath != "" {
		opts = append(opts, huh.NewOption(
			fmt.Sprintf("Use my default key  (%s)", defaultPath),
			defaultPath,
		))
	}
	ssmxKeyPath := filepath.Join(os.Getenv("HOME"), ".ssmx", "ssh_key")
	opts = append(opts, huh.NewOption(
		fmt.Sprintf("Generate a new ssmx-managed key  (%s)", ssmxKeyPath),
		"__generate__",
	))

	var selected string
	if err := huh.NewSelect[string]().
		Title("Which SSH key should ssmx use for SSH connections?").
		Options(opts...).
		Value(&selected).
		Run(); err != nil {
		return "", err
	}

	if selected == "__generate__" {
		_, resolvedPath, err := sshpkg.LoadOrGenerateKey("")
		if err != nil {
			return "", err
		}
		fmt.Printf("%s  Generated %s\n", tui.StyleSuccess.Render("ok"), resolvedPath)
		return resolvedPath, nil
	}
	return selected, nil
}
